### PR TITLE
Create 2020-05-20 ZLC Agenda

### PR DESCRIPTION
**Pull request by armstro**

### CODE REVIEW

**Comment by zFernand0** [comment]
@armstro, If you'd like to get rid of the DCO issues, feel free to give the [DCO GitHub Chrome Extension](https://chrome.google.com/webstore/detail/dco-github-ui/onhgmjhnaeipfgacbglaphlmllkpoijo?hl=en) a try :yum:

Also, having files in Markdown format (`.md`) could be helpful for readers of the agenda. 😋

**Comment by armstro** [comment]
@zFernand0 Thanks for message 
1) do you happen to know of a DCO add-on for Firefox? Firefox is my primary browser for all work items and I have not found a popular/trusted/recommend one for Firefox - I don't want to switch to Chrome just to work with github (plus I have a zenhub plug in already on Firefox that I am trying to use) 
2) I am a github novice (as are some of the others on the ZLC) - using github for all the meeting agendas,  mins, records, etc. is not our first choice but we are trying to go with what is popular with the community. I am looking for a user friendly front end to github that I could create meeting agenda and mins in a format that could use (like numbered outline, tabs/indentions, etc.) and have the tool generate the markup file. I tried hackmd.io but could not get it to work - now trying to switch to VS Code.......if you have a tool you'd recommend please do

**Comment by zFernand0** [comment]
1. I'm afraid I don't use Firefox much, but maybe other can confirm if this is a good one to use?
https://addons.mozilla.org/en-US/firefox/addon/scott-rigby/

2. I (personally) like the way VSCode allows for markdown editing and how other extensions help export it to other formats if needed. Whichever tool you decide to use, I'm sure it will be fine as long as the file name ends in `.md`

I do appreciate you considering new tools! :yum:

**Comment by RASakach** [comment]
@MarkAckert can you help merge this "branch" that has been acting as the master branch for several years, into master?  I'd like to begin my tenure as ZAC leader using the main branch.

**Pull request closed without merging**
